// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-sIoDHAGqpb7btx6IFOQHTH5RoRqJRIY',
    appId: '1:415228559554:web:c4adafd5c76f95b238fb5b',
    messagingSenderId: '415228559554',
    projectId: 'mynotesmynotes-0407',
    authDomain: 'mynotesmynotes-0407.firebaseapp.com',
    storageBucket: 'mynotesmynotes-0407.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_lKeK-zmDNs4oBMoYK8GMLsQiCz-nh7Y',
    appId: '1:415228559554:android:8ee36126ccdeb84238fb5b',
    messagingSenderId: '415228559554',
    projectId: 'mynotesmynotes-0407',
    storageBucket: 'mynotesmynotes-0407.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANYVkxnZxOzLMvYQG6eBSC_GxD9Oyo2gw',
    appId: '1:415228559554:ios:e1882790af0b871638fb5b',
    messagingSenderId: '415228559554',
    projectId: 'mynotesmynotes-0407',
    storageBucket: 'mynotesmynotes-0407.appspot.com',
    iosClientId:
        '415228559554-n9d4gq8ivukfmtgkfl66k0n5tcnst0fd.apps.googleusercontent.com',
    iosBundleId: 'com.onetest.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANYVkxnZxOzLMvYQG6eBSC_GxD9Oyo2gw',
    appId: '1:415228559554:ios:e1882790af0b871638fb5b',
    messagingSenderId: '415228559554',
    projectId: 'mynotesmynotes-0407',
    storageBucket: 'mynotesmynotes-0407.appspot.com',
    iosClientId:
        '415228559554-n9d4gq8ivukfmtgkfl66k0n5tcnst0fd.apps.googleusercontent.com',
    iosBundleId: 'com.onetest.mynotes',
  );
}
